name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - fumadocs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build all snippet projects
        run: |
          for proj in snippets/*/*.fsproj; do
            echo "Building $proj"
            dotnet build "$proj"
          done

      - name: Copy all wwwroot folders to output
        run: |
          mkdir -p out/snippets
          for dir in snippets/*; do
            if [ -d "$dir/wwwroot" ]; then
              name=$(basename "$dir")
              mkdir -p "out/snippets/$name"
              cp -r "$dir/wwwroot/"* "out/snippets/$name/"
            fi
          done

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
