name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - fumadocs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: |
            dotnet tool restore
            dotnet paket restore
        working-directory: ./snippets

      - name: Build and Resolve Femto for all snippet projects
        run: |
          for proj in snippets/*/*.*proj; do
            echo "Building and Resolving $proj"
            dotnet build "$proj" -c Release
          done

      - name: Copy all wwwroot folders to output
        run: |
          mkdir -p out/snippets
          for dir in snippets/*; do
            if [ -d "$dir/wwwroot" ]; then
              name=$(basename "$dir")
              mkdir -p "out/snippets/$name"
              cp -r "$dir/wwwroot/"* "out/snippets/$name/"
            fi
          done

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
  link-checker:
    needs: deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://docs.websharper.com/
          cmd_params: '--buffer-size=8192 --max-connections=5 --color=always --timeout=30 --exclude="(https://docs.websharper.com/cdn-cgi|https://github.com/reduxjs/redux-devtools/|https://en.wikibooks.org/wiki/TeX/def)|https://docs.websharper.com/_next/static/media/small-file-suggestion\.d9761795\.gif)"'
